{ config, pkgs, ... }:

{
  imports = [
    # Hardware configuration (generated by nixos-generate-config)
    ./hardware-configuration.nix

    # Shared modules
    ../../modules/common
    ../../modules/security
    ../../modules/development
    ../../modules/users
  ];

  # Hostname
  networking.hostName = "dev-machine-2";

  # User configuration
  # IMPORTANT: Replace 'youruser' with your actual username
  # DO NOT commit real usernames or SSH keys to this public repo
  # Consider using a secrets management solution like sops-nix
  users.users.youruser = {
    isNormalUser = true;
    description = "Dev User";
    extraGroups = [ "networkmanager" "wheel" "docker" "libvirtd" ];
    shell = pkgs.zsh;
    # DO NOT add SSH keys here in a public repo!
    # Instead, add them manually after installation or use a private secrets repo
    # openssh.authorizedKeys.keys = [ ];
  };

  # Machine-specific firewall rules
  networking.firewall = {
    allowedTCPPorts = [
      # Add your specific ports here
      # 8080  # Example: development server
      # 3000  # Example: Node.js app
    ];
    allowedUDPPorts = [ ];
  };

  # Machine-specific packages
  environment.systemPackages = with pkgs; [
    # Add machine-specific packages here
  ];

  # Optional: Enable X11 windowing system
  # services.xserver.enable = true;
  # services.xserver.displayManager.gdm.enable = true;
  # services.xserver.desktopManager.gnome.enable = true;

  # Optional: Enable CUPS to print documents
  # services.printing.enable = true;

  # Optional: Enable sound
  # sound.enable = true;
  # hardware.pulseaudio.enable = true;
  # OR
  # security.rtkit.enable = true;
  # services.pipewire = {
  #   enable = true;
  #   alsa.enable = true;
  #   alsa.support32Bit = true;
  #   pulse.enable = true;
  # };

  # This value determines the NixOS release from which the default
  # settings for stateful data, like file locations and database versions
  # on your system were taken. Don't change this unless you know what you're doing.
  system.stateVersion = "24.11";
}
